# Generated by Django 2.1.7 on 2019-03-28 07:08

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bug',
            fields=[
                ('bug_id', models.AutoField(primary_key=True, serialize=False)),
                ('bug_title', models.CharField(max_length=200)),
                ('bugDescription', models.CharField(max_length=1000)),
                ('bug_status', models.CharField(choices=[('L', 'LIVE'), ('A', 'ARCHIVED'), ('R', 'RESOLVED')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='company',
            fields=[
                ('companyName', models.CharField(max_length=50)),
                ('companyId', models.AutoField(primary_key=True, serialize=False)),
                ('companyLogo', models.ImageField(blank=True, upload_to='company_logo')),
            ],
        ),
        migrations.CreateModel(
            name='developer',
            fields=[
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('profile', models.CharField(choices=[('SSE', 'Senior Software Engineer'), ('ST', 'Software Tester'), ('SA', 'Software Architect'), ('SE', 'Software Engineer'), ('SD', 'Software Developer'), ('SY', 'Software Analyst'), ('BA', 'Business analyst'), ('TS', 'Technical support')], max_length=2)),
                ('auth_id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='profile_image')),
                ('profileAuth', models.CharField(choices=[('U', 'user'), ('D', 'developer')], max_length=1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.company')),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('postId', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('postTitle', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=1000)),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.bug')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.developer')),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('project_name', models.CharField(max_length=200)),
                ('projectDescription', models.TextField(default='Lorem Ipsum')),
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(default=datetime.datetime.today)),
                ('company', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='mysite.company')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('rating', models.DecimalField(decimal_places=2, default='', max_digits=5)),
                ('auth_id', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='profile_image')),
            ],
        ),
        migrations.AddField(
            model_name='bug',
            name='bugAssociation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.developer'),
        ),
        migrations.AddField(
            model_name='bug',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.project'),
        ),
    ]
