# Generated by Django 2.1.7 on 2019-03-30 15:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(8000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('message', models.TextField()),
            ],
        ),
    ]
