# Generated by Django 2.1.7 on 2019-03-30 17:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='abc@xyz.com', max_length=30, validators=[django.core.validators.EmailValidator]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.BigIntegerField(default=9972207484, validators=[django.core.validators.MinValueValidator(8000000000), django.core.validators.MaxValueValidator(9999999999)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=30, validators=[django.core.validators.EmailValidator(code=None, message='Enter Valid email', whitelist=None)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
