# Generated by Django 2.1.7 on 2019-03-30 19:11

import datetime
from django.db import migrations, models
import mysite.models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20190330_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rating',
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=datetime.date.today, validators=[mysite.models.project.validateDate]),
        ),
    ]
