# Generated by Django 2.1.7 on 2019-03-31 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20190330_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
        migrations.AddField(
            model_name='bug',
            name='postedOn',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='profile',
            field=models.CharField(choices=[('SSE', 'Senior Software Engineer'), ('ST', 'Software Tester'), ('SA', 'Software Architect'), ('SE', 'Software Engineer'), ('SD', 'Software Developer'), ('SY', 'Software Analyst'), ('BA', 'Business analyst'), ('TS', 'Technical support'), ('US', 'User')], max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='auth_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
