# Generated by Django 2.1.7 on 2019-04-01 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_auto_20190331_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='voted',
            fields=[
                ('voteType', models.CharField(choices=[('U', 'Upvote'), ('D', 'Downvote')], max_length=1)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('postA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.post')),
                ('userA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.developer')),
            ],
        ),
    ]
