# Generated by Django 2.1.7 on 2019-04-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_auto_20190401_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='rating',
            field=models.FloatField(default=2.5),
        ),
    ]
