# Generated by Django 2.2.2 on 2020-03-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_auto_20190401_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='companyLogo',
            field=models.ImageField(default='https://images.unsplash.com/photo-1494253109108-2e30c049369b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80', upload_to='company_logo'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='image',
            field=models.ImageField(default='https://images.unsplash.com/photo-1494253109108-2e30c049369b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80', upload_to='profile_image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='https://images.unsplash.com/photo-1494253109108-2e30c049369b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80', upload_to='profile_image'),
        ),
    ]
