# Generated by Django 2.2.2 on 2020-03-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_auto_20200316_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='profile',
            field=models.CharField(choices=[('SS', 'Senior Software Engineer'), ('ST', 'Software Tester'), ('SA', 'Software Architect'), ('SE', 'Software Engineer'), ('SD', 'Software Developer'), ('SY', 'Software Analyst'), ('BA', 'Business analyst'), ('TS', 'Technical support'), ('US', 'User')], max_length=2),
        ),
    ]
